### ISSUE TITLE
This channel already has 5 subscriptions! Please delete some before adding more.

### ISSUE THREAD

**Issue by FillingTheVoidOnYT** [janderedev/feeds-bot#1]
Just a feature request to add more ability to have more subscriptions

**Comment by sussycatgirl** [comment]
That's a limitation I can easily raise. What would a sensible limit be in your eyes?

**Comment by FillingTheVoidOnYT** [comment]
> That's a limitation I can easily raise. What would a sensible limit be in your eyes?

i think a server limit as a whole should be good or 5five per channel. maybe asking an question that asks the users 5 per channel or etc per server

**Comment by sussycatgirl** [comment]
Sorry, I forgot to get back to you. I increased the limit to 20 per channel a couple months ago - I hope that's enough for most use cases!
