### ISSUE TITLE
You cannot add a feed in a group channel

### ISSUE THREAD

**Issue by searinminecraft** [janderedev/feeds-bot#6]
If you attempt to add a feed in a group channel, it refuses because the user (the owner in this case) requires "Manage Server" which makes no sense.

![image](https://user-images.githubusercontent.com/114207889/233757987-b7567123-ae5b-475a-a511-e4ec38a25d7c.png)

**Comment by sussycatgirl** [comment]
My bad, I never considered group channels :skull:
